<?php
/**
 * @file
 * Module file for the Wanderers' Flight Club sendgrid module, contains all the main hooks and logic functions.
 */

/**
 * Implements hook_theme().
 */
function wfc_sendgrid_theme($existing, $type, $theme, $path)
{
  return [
    'email_confirmation_template' => [
      'variables' => ['vars' => NULL],
      'template' => 'email-confirmation-template'
    ],
    'new_user_template' => [
      'variables' => ['vars' => NULL],
      'template' => 'new-user-template'
    ]
  ];
}
