<?php
/**
 * @file
 * Module file for the Wanderers' Flight Club sendgrid module, contains all the main hooks and logic functions.
 */

/**
 * Implements hook_theme().
 */
function wfc_sendgrid_theme($existing, $type, $theme, $path)
{
  return array(
    'email_confirmation_template' => array(
      'variables' => array('vars' => NULL),
      'template' => 'email-confirmation-template'
    ),
  );
}
